services:
  trainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./configs:/app/configs
      - ./checkpoints:/mnt/checkpoints
      - ./data:/app/data
    env_file:
      - path: .env
        required: false
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
